pipeline:
  build:
    image: kkarczmarczyk/node-yarn:6.9-slim
    commands:
      - yarn install
      - yarn run build
  build2:
    image: kkarczmarczyk/node-yarn:6.9-slim
    commands:
      - yarn install
      - yarn run build
